name: book_reader
description: "A comprehensive PDF and EPUB reader app with file manager integration."
publish_to: 'none'

version: 2.0.0+2

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core functionality
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3
  path_provider: ^2.1.4
  provider: ^6.1.2
  window_manager: ^0.3.9
  path: ^1.9.0

  # PDF/EPUB readers
  flutter_pdfview: ^1.3.2
  syncfusion_flutter_pdfviewer: ^27.0.0
  epubx: ^4.0.0

  # HTML rendering
  flutter_html: ^3.0.0-beta.2

  # Essential utilities
  archive: ^3.6.1
  webview_flutter: ^4.7.0
  webview_windows: ^0.2.0
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/js/
    - assets/epub_reader.html
